package net.OnBoarding;

/**
 * Created by Lucas on 29/07/2016.
 */
//
// Copyright 2016 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-android v0.7
//

import android.app.Activity;
import android.app.AlertDialog;
import android.app.ProgressDialog;
import android.content.BroadcastReceiver;
import android.content.Context;
import android.content.Intent;
import android.content.IntentFilter;
import android.content.res.Resources;
import android.graphics.Color;
import android.graphics.PorterDuff;
import android.graphics.RectF;
import android.graphics.Typeface;
import android.graphics.drawable.Drawable;
import android.os.AsyncTask;
import android.os.Build;
import android.os.Bundle;
import android.support.v4.app.Fragment;
import android.support.v4.app.FragmentManager;
import android.support.v4.app.FragmentPagerAdapter;
import android.support.v4.content.LocalBroadcastManager;
import android.support.v4.util.SparseArrayCompat;
import android.support.v4.view.ViewPager;
import android.support.v7.app.AppCompatActivity;
import android.support.v7.widget.Toolbar;
import android.util.Log;
import android.util.TypedValue;
import android.view.Menu;
import android.view.MenuItem;
import android.view.View;
import android.widget.AbsListView;
import android.widget.ImageView;
import android.widget.ScrollView;
import android.widget.TextView;
import android.widget.Toast;

import com.amazonaws.AmazonClientException;
import com.amazonaws.mobileconnectors.cognito.Dataset;
import com.amazonaws.mobileconnectors.cognito.DefaultSyncCallback;
import com.amazonaws.mobileconnectors.cognito.Record;
import com.amazonaws.mobileconnectors.cognito.SyncConflict;
import com.amazonaws.mobileconnectors.cognito.exceptions.DataStorageException;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBMapper;
import com.jeremyfeinstein.slidingmenu.lib.SlidingMenu;
import com.viewpagerindicator.CirclePageIndicator;

import net.amazonaws.mobile.AWSMobileClient;
import net.amazonaws.mobile.user.IdentityManager;
import net.astuetz.PagerSlidingTabStrip;
import net.egobeta.ego.EgoMap;
import net.egobeta.ego.Fragments.Fragment_Main;
import net.egobeta.ego.Fragments.Fragment_Main_Friends;
import net.egobeta.ego.Fragments.ScrollTabHolderFragment;
import net.egobeta.ego.Interfaces.ScrollTabHolder;
import net.egobeta.ego.PushListenerService;
import net.egobeta.ego.R;
import net.egobeta.ego.demo.UserSettings;
import net.flavienlaurent.notboringactionbar.AlphaForegroundColorSpan;

import java.util.List;




public class Main_Onboarding extends AppCompatActivity implements ScrollTabHolder, ViewPager.OnPageChangeListener, View.OnClickListener {

    //AWS Variables
    AWSMobileClient awsMobileClient;
    static DynamoDBMapper mapper;
    public static IdentityManager identityManager; //The identity manager used to keep track of the current user account.


    //Other variables
    private final static String LOG_TAG = Main_Onboarding.class.getSimpleName(); //Class name for log messages.
    Typeface typeface;
    private TypedValue mTypedValue = new TypedValue();
    private PagerAdapter mPagerAdapter; //The pager adapter, which provides the pages to the view pager widget.
    ScrollTabHolderFragment fragment;

    private Resources resources;
    static Context context;
    private static AlphaForegroundColorSpan mAlphaForegroundColorSpan;
    static EgoMap egoMap;
//    static UserLocation userLocation;
    static Thread thread;
    private static Activity activity;
//    static EgoStreamViewAdapter2 adapter;

    //Number Variables
    private static int mMinHeaderTranslation;
    private int mActionBarHeight;
    public int mMinHeaderHeight;
    private int mHeaderHeight;
    private static RectF mRect1 = new RectF();
    private static RectF mRect2 = new RectF();

    //View item variables
    private static View mHeader;
    private static ImageView home_menu_image;
    private static ImageView home_menu_image2;
    private ImageView mHeaderPicture;
    public Drawable upArrow;
    public static ImageView egoLogo;
    public static ScrollView scrollView;
    private SlidingMenu slidingMenu;
    private ViewPager mViewPager;
    private static Toolbar toolbar;
    public PagerSlidingTabStrip mPagerSlidingTabStrip;
    private static TextView toolbarTitle;
    private static AbsListView absListView;
    static CirclePageIndicator pageIndicator;



    @Override
    protected void onCreate(final Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        activity = this;
        /** AWS Stuffs **/
        // Obtain a reference to the mobile client. It is created in the Application class,
        // but in case a custom Application class is not used, we initialize it here if necessary.
        AWSMobileClient.initializeMobileClientIfNecessary(this);
        // Obtain a reference to the mobile client. It is created in the Application class.
        awsMobileClient = AWSMobileClient.defaultMobileClient();
        // Obtain a reference to the identity manager.
        identityManager = awsMobileClient.getIdentityManager();

        //Initialize the mapper for DynamoDB
        mapper = AWSMobileClient.defaultMobileClient().getDynamoDBMapper();

        /****************/
        setContentView(R.layout.activity_main_onboarding);
        context = getApplicationContext();

        resources = getResources();

        /**Initialize font*/
        typeface = Typeface.createFromAsset(getAssets(), "fonts/ChaletNewYorkNineteenEighty.ttf");

        /**Initialize dimension variables for the animations*/
        initializeDimensionItems();

        /**Initialize view item variables*/
        initializeViewItems();

        /**Set up the ViewPager and PagerAdapter*/
        mViewPager = (ViewPager) findViewById(R.id.pager);
        mViewPager.setOffscreenPageLimit(3);
        mPagerAdapter = new PagerAdapter(getSupportFragmentManager());
        mPagerAdapter.setTabHolderScrollingContent(this);
        mViewPager.setAdapter(mPagerAdapter);

        /**Set up the SlidingTabStrip*/
        initializeSlidingTabStrip();



        /**Create top toolbar/menu bar*/
        toolbar = (Toolbar) findViewById(R.id.toolbar);
        setSupportActionBar(toolbar);
        assert getSupportActionBar() != null;
        getSupportActionBar().setDisplayHomeAsUpEnabled(true);
        toolbar.setOnClickListener(this);

        /**Get rid of the default arrow image*/
        removeDefaultMenuButton();


        /*Bind the Page indicator to the adapter*/
        pageIndicator = (CirclePageIndicator)findViewById(R.id.titles);
        int tabPageColor = Color.parseColor("#5055C1AD");
        int tabFillColor = Color.parseColor("#55C1AD");
        pageIndicator.setStrokeColor(tabPageColor);
        pageIndicator.setFillColor(tabFillColor);
        pageIndicator.setPageColor(tabPageColor);
        pageIndicator.setExtraSpacing(15f);
        pageIndicator.setViewPager(mViewPager);






        //Fire the ego map on create method
        theMapOnCreateMethod();

        //GetThe first batch of nearby users
        getNearbyUsers(0);
    }

    public static void createUpdateUserLocation(){
        AmazonClientException lastException = null;
        IdentityManager identityManager2 = AWSMobileClient.defaultMobileClient()
                .getIdentityManager();



        try {
//            mapper.save(userLocation);
        } catch (final AmazonClientException ex) {
            Log.e("AMAZON EXCEPTION", "Failed saving item : " + ex.getMessage(), ex);
            lastException = ex;
        }

        if (lastException != null) {
            // Re-throw the last exception encountered to alert the user.
            throw lastException;
        }

    }


//     public class SaveToDB extends AsyncTask<Void, Void, Void> {
//
//
//        @Override
//        protected Void doInBackground(Void... params) {
//            try{
//                mapper.save(bookToSave);
//            } catch (AmazonClientException ex){
//                ex.printStackTrace();
//            }
//
//            return null;
//        }
//
//        @Override
//        protected void onPostExecute(Void aVoid) {
//            super.onPostExecute(aVoid);
//            Toast.makeText(getActivity(), "Successfully saved book to db", Toast.LENGTH_SHORT).show();
//        }
//    }




    /**Created from the AWS demo app**/
    /** Sync user's preferences only if user is signed in **/
    private void syncUserSettings() {
        // sync only if user is signed in
        if (AWSMobileClient.defaultMobileClient().getIdentityManager().isUserSignedIn()) {
            final UserSettings userSettings = UserSettings.getInstance(getApplicationContext());
            userSettings.getDataset().synchronize(new DefaultSyncCallback() {
                @Override
                public void onSuccess(final Dataset dataset, final List<Record> updatedRecords) {
                    super.onSuccess(dataset, updatedRecords);
                    Log.d(LOG_TAG, "successfully synced user settings");

                    runOnUiThread(new Runnable() {
                        @Override
                        public void run() {
                            loadUserSettings();

                        }
                    });


                    //If firstTimeUser = 0
                    // go to OnBoardingActivity
                    //else
                    // stay on current activity and

                }
            });
        }
    }

    private void loadUserSettings() {
        final UserSettings userSettings = UserSettings.getInstance(context);
        final Dataset dataset = userSettings.getDataset();
        final ProgressDialog dialog = ProgressDialog.show(activity,
                getString(R.string.settings_fragment_dialog_title),
                getString(R.string.settings_fragment_dialog_message));
        Log.d(LOG_TAG, "Loading user settings from remote");
        dataset.synchronize(new DefaultSyncCallback() {
            @Override
            public void onSuccess(final Dataset dataset, final List<Record> updatedRecords) {
                super.onSuccess(dataset, updatedRecords);
                userSettings.loadFromDataset();
                if (userSettings.getNewUser() == 0) {
//                    updateUI(dialog, 1);
                    //Go to OnBaording
                } else {
                    updateUI(dialog, 0);
                }
                ;
            }

            @Override
            public void onFailure(final DataStorageException dse) {
                Log.w(LOG_TAG, "Failed to load user settings from remote, using default.", dse);
                updateUI(dialog, 3);
            }

            @Override
            public boolean onDatasetsMerged(final Dataset dataset,
                                            final List<String> datasetNames) {
                // Handle dataset merge. One can selectively copy records from merged datasets
                // if needed. Here, simply discard merged datasets
                for (String name : datasetNames) {
                    Log.d(LOG_TAG, "found merged datasets: " + name);
                    AWSMobileClient.defaultMobileClient().getSyncManager().openOrCreateDataset(name).delete();
                }
                return true;
            }
        });
    }

    private void updateUI(final ProgressDialog dialog, final int isFirstTimeUSer) {
        activity.runOnUiThread(new Runnable() {
            @Override
            public void run() {
                if (dialog != null) {
                    dialog.dismiss();
                }
                if (isFirstTimeUSer == 0) {
                    Toast.makeText(activity, "not FirstTimeUser", Toast.LENGTH_SHORT).show();
                } else if (isFirstTimeUSer == 1) {
                    Toast.makeText(activity, "FirstTimeUser", Toast.LENGTH_SHORT).show();
                } else {
                    Toast.makeText(activity, "Failure updating", Toast.LENGTH_SHORT).show();
                }
                setFirstTimeUser(isFirstTimeUSer);
            }
        });
    }

    private void setFirstTimeUser(int firstTime) {
        final UserSettings userSettings = UserSettings.getInstance(context);
        userSettings.setNewUser(firstTime);

        new AsyncTask<Void, Void, Void>() {
            @Override
            protected Void doInBackground(final Void... params) {
                userSettings.saveToDataset();
                return null;
            }

            @Override
            protected void onPostExecute(final Void aVoid) {

                // update color
//                ((MainActivity) getActivity()).updateColor();

                // save user settings to remote on background thread
                userSettings.getDataset().synchronize(new Dataset.SyncCallback() {
                    @Override
                    public void onSuccess(Dataset dataset, List<Record> updatedRecords) {
                        Log.d(LOG_TAG, "onSuccess - dataset updated");

                    }

                    @Override
                    public boolean onConflict(Dataset dataset, List<SyncConflict> conflicts) {
                        Log.d(LOG_TAG, "onConflict - dataset conflict");
                        return false;
                    }

                    @Override
                    public boolean onDatasetDeleted(Dataset dataset, String datasetName) {
                        Log.d(LOG_TAG, "onDatasetDeleted - dataset deleted");
                        return false;
                    }

                    @Override
                    public boolean onDatasetsMerged(Dataset dataset, List<String> datasetNames) {
                        Log.d(LOG_TAG, "onDatasetsMerged - datasets merged");
                        return false;
                    }

                    @Override
                    public void onFailure(DataStorageException dse) {
                        Log.e(LOG_TAG, "onFailure - " + dse.getMessage(), dse);
                    }
                });
            }
        }.execute();
    }

    //Initialize dimension variables for the animations
    private void initializeDimensionItems() {
        mMinHeaderHeight = getResources().getDimensionPixelSize(R.dimen.min_header_height);
        mHeaderHeight = getResources().getDimensionPixelSize(R.dimen.header_height);
        mMinHeaderTranslation = -mMinHeaderHeight + getActionBarHeight();
    }

    //Initialize view item variables
    private void initializeViewItems(){
        mHeader = findViewById(R.id.header); /**ENTIRE HEADER**/
        home_menu_image = (ImageView) findViewById(R.id.toolbar_icon); /**HEADER - HOME MENU IMAGE**/
        home_menu_image2 = (ImageView) findViewById(R.id.toolbar_icon2); /**HEADER - HOME MENU IMAGE**/
        mHeaderPicture = (ImageView) findViewById(R.id.header_picture); /**HEADER - BLURRED BACKGROUND**/

        egoLogo = (ImageView) findViewById(R.id.ego_logo); /**HEADER - PROFILE PICTURE**/
        toolbarTitle = (TextView) findViewById(R.id.toolbar_title);
    }

    //Method for header animation
    public int getActionBarHeight() {
        if (mActionBarHeight != 0) {
            return mActionBarHeight;
        }
        getTheme().resolveAttribute(android.R.attr.actionBarSize, mTypedValue, true);
        mActionBarHeight = TypedValue.complexToDimensionPixelSize(mTypedValue.data, getResources().getDisplayMetrics());
        return mActionBarHeight;
    }

    //Set up the SlidingTabStrip
    private void initializeSlidingTabStrip() {
        mPagerSlidingTabStrip = (PagerSlidingTabStrip) findViewById(R.id.tabs);
        mPagerSlidingTabStrip.setViewPager(mViewPager);
        mPagerSlidingTabStrip.getTabBackground();
        mPagerSlidingTabStrip.setOnPageChangeListener(this);
        mAlphaForegroundColorSpan = new AlphaForegroundColorSpan(0xffffffff);
    }

    //Using custom image view as home as up indicator, this gets rid of the default arrow image
    private void removeDefaultMenuButton(){

        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
            upArrow = getDrawable(R.drawable.back_arrow_transparent);
        } else {
            upArrow = getResources().getDrawable(R.drawable.back_arrow_transparent);
        }
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
            upArrow.setColorFilter(getColor(R.color.transparentBackground), PorterDuff.Mode.SRC_ATOP);
        }
        getSupportActionBar().setHomeAsUpIndicator(upArrow);
    }

    //Method to detect the scroll value of the Y axis
    public int getScrollY(AbsListView view) {
        View c = view.getChildAt(0);
        if (c == null) {
            return 0;
        }
        int firstVisiblePosition = view.getFirstVisiblePosition();
        int top = c.getTop();
        int headerHeight = 0;
        if (firstVisiblePosition >= 1) {
            headerHeight = mHeaderHeight;
        }
        return -top + firstVisiblePosition * c.getHeight() + headerHeight;
    }

    //Method for header animation
    public static float clamp(float value, float max, float min) {
        return Math.max(Math.min(value, min), max);
    }

    //Method to animate the title fade in/out
    private static void setTitleAlpha(float alpha) {
//        mAlphaForegroundColorSpan.setAlpha(alpha);
//        mSpannableString.setSpan(mAlphaForegroundColorSpan, 0, mSpannableString.length(), Spannable.SPAN_EXCLUSIVE_EXCLUSIVE);
        toolbar.setTitle(" ");
//        egoLogo.setAlpha(alpha * 1);
    }

    //Method to animate the homeAsUp indicator fade in/out
    private static void setHomeAsUpAlpha(float alpha) {
        toolbar.setAlpha(alpha * 1);
        egoLogo.setAlpha(alpha * 1);
        pageIndicator.setAlpha(alpha * 1);
        mHeader.setAlpha(alpha * 1);
    }




    @Override
    protected void onPause() {
        super.onPause();

        // Obtain a reference to the mobile client.
        final AWSMobileClient awsMobileClient = AWSMobileClient.defaultMobileClient();

        // pause/resume Mobile Analytics collection
        awsMobileClient.handleOnPause();

        // unregister notification receiver
        LocalBroadcastManager.getInstance(this).unregisterReceiver(notificationReceiver);
        LocalBroadcastManager.getInstance(this).unregisterReceiver(settingsChangedReceiver);
    }

    @Override
    protected void onResume() {
        super.onResume();
        mHeaderPicture = (ImageView) findViewById(R.id.header_picture); /**HEADER - BLURRED BACKGROUND**/


        final AWSMobileClient awsMobileClient = AWSMobileClient.defaultMobileClient();

        // pause/resume Mobile Analytics collection
        awsMobileClient.handleOnResume();

        // register notification receiver
        LocalBroadcastManager.getInstance(this).registerReceiver(notificationReceiver,
                new IntentFilter(PushListenerService.ACTION_SNS_NOTIFICATION));
        // register settings changed receiver.
        LocalBroadcastManager.getInstance(this).registerReceiver(settingsChangedReceiver,
                new IntentFilter(UserSettings.ACTION_SETTINGS_CHANGED));
//        updateColor();

//Sync the user's privacy settings and detect if the user is first time.
        syncUserSettings();


//        theMapOnResumeMethod();
        getNearbyUsers(0);
    }

    @Override
    protected void onStart() {
        super.onStart();
        mHeaderPicture = (ImageView) findViewById(R.id.header_picture);
        theMapOnStartMethod();

    }

    @Override
    public void onBackPressed() {
        final FragmentManager fragmentManager = this.getSupportFragmentManager();

//        if (navigationDrawer.isDrawerOpen()) {
//            navigationDrawer.closeDrawer();
//            return;
//        }

        /*if (fragmentManager.getBackStackEntryCount() == 0) {
            if (fragmentManager.findFragmentByTag(HomeDemoFragment.class.getSimpleName()) == null) {
                final Class fragmentClass = HomeDemoFragment.class;
                // if we aren't on the home fragment, navigate home.
                final Fragment fragment = Fragment.instantiate(this, fragmentClass.getName());

                fragmentManager
                    .beginTransaction()
                    .replace(R.id.main_fragment_container, fragment, fragmentClass.getSimpleName())
                    .setTransition(FragmentTransaction.TRANSIT_FRAGMENT_OPEN)
                    .commit();

                // Set the title for the fragment.
                *//*final ActionBar actionBar = this.getSupportActionBar();
                if (actionBar != null) {
                    actionBar.setTitle(getString(R.string.app_name));
                }*//*
                return;
            }
        }*/
        super.onBackPressed();
    }

    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
//		return super.onCreateOptionsMenu(menu);
        getMenuInflater().inflate(R.menu.menu_main1, menu);
        return true;
    }

    /************************************** IMPLEMENTED METHODS ******************************************/
    /***********************************************************************************************/

    @Override
    public void onClick(final View v) {
        switch(v.getId()){
            case R.id.toolbar:
                absListView.post(new Runnable() {
                    @Override
                    public void run() {
                        absListView.smoothScrollToPosition(0);
                    }
                });
                Toast.makeText(this, "toolbar clicked mainActivity", Toast.LENGTH_SHORT).show();
                break;
        }

    }

    public static void backToTop(){
        absListView.post(new Runnable() {
            @Override
            public void run() {
                absListView.smoothScrollToPosition(0);

            }
        });
    }

    @Override
    public void onPageScrolled(int position, float positionOffset, int positionOffsetPixels) {

    }

    @Override
    public void onPageSelected(int position) {
        SparseArrayCompat<ScrollTabHolder> scrollTabHolders = mPagerAdapter.getScrollTabHolders();
        ScrollTabHolder currentHolder = scrollTabHolders.valueAt(position);

        currentHolder.adjustScroll((int) (mHeader.getHeight() + mHeader.getTranslationY()));

    }

    @Override
    public void onPageScrollStateChanged(int state) {

    }

    @Override
    public void adjustScroll(int scrollHeight) {

    }

    @Override
    public boolean onOptionsItemSelected(final MenuItem item) {
        // Handle action bar item clicks here excluding the home button.
        switch (item.getItemId()) {
            case android.R.id.home:
                slidingMenu.toggle();
                return true;
        }

        return super.onOptionsItemSelected(item);
    }

    @Override
    public void onScroll(AbsListView view, int firstVisibleItem, int visibleItemCount, int totalItemCount, int pagePosition) {
        if (mViewPager.getCurrentItem() == pagePosition) {
            absListView = view;
            int scrollY = getScrollY(view);

            mHeader.setTranslationY(Math.max(-scrollY, mMinHeaderTranslation));
            float ratio = clamp(mHeader.getTranslationY() / mMinHeaderTranslation, 0.0f, 1.0f);

//            interpolate(egoLogo, getHomeMenuImageIconView(), sSmoothInterpolator.getInterpolation(ratio));
            setTitleAlpha(clamp(5.0F * ratio - 4.0F, 0.0F, 1.0F));
            setHomeAsUpAlpha(clamp((5.0F * ratio - 4.0F) * -1, 0.0F, 1.0F));
        }
    }


    /************************************** INNER CLASSES ******************************************/
    /***********************************************************************************************/

//    //A Pager adapter that represents 2 ScreenSlidePageFragment objects, in sequence.
//    public class ScreenSlidePagerAdapter extends FragmentPagerAdapter {
//        int count = 0;
//        public ScreenSlidePagerAdapter(FragmentManager fm) {
//            super(fm);
//        }
//
//        //        What happens when page is swiped?
//        @Override
//        public Fragment getItem(int position) {
//            switch(position){
//                case 1:
//                    egoFriendsFragment = new EgoFriendsFragment();
//                    return egoFriendsFragment;
//                default: break;
//            }
//            egoStreamFragment = new EgoStreamFragment();
//            return egoStreamFragment;
//        }
//
//        @Override
//        public int getCount() {
//            return 2;
//        }
//    }

    //PagerAdapter for the sliding pages under user profile
    public class PagerAdapter extends FragmentPagerAdapter {

        private SparseArrayCompat<ScrollTabHolder> mScrollTabHolders;
        private final String[] TITLES = {"1", "2", "3", "4"};
//        private final String[] TITLES = {" "};

        private ScrollTabHolder mListener;

        public PagerAdapter(FragmentManager fm) {
            super(fm);
            mScrollTabHolders = new SparseArrayCompat<ScrollTabHolder>();
        }

        public void setTabHolderScrollingContent(ScrollTabHolder listener) {
            mListener = listener;
        }

        @Override
        public CharSequence getPageTitle(int position) {
            return TITLES[position];
        }


        @Override
        public int getCount() {
            return TITLES.length;
        }


        @Override
        public Fragment getItem(int position) {
            if(position == 0){
                fragment = (ScrollTabHolderFragment) Fragment_Main.newInstance(Main_Onboarding.this, context, position, toolbar);
            } else {
                fragment = (ScrollTabHolderFragment) Fragment_Main_Friends.newInstance(Main_Onboarding.this, context, position, toolbar);
            }


            mScrollTabHolders.put(position, fragment);
            if (mListener != null) {
                fragment.setScrollTabHolder(mListener);

            }

            return fragment;

        }

        public SparseArrayCompat<ScrollTabHolder> getScrollTabHolders() {
            return mScrollTabHolders;
        }

    }










    /************************************** FINAL METHODS ******************************************/
    /***********************************************************************************************/

    private final BroadcastReceiver notificationReceiver = new BroadcastReceiver() {
        @Override
        public void onReceive(Context context, Intent intent) {
            Log.d(LOG_TAG, "Received notification from local broadcast. Display it in a dialog.");

            Bundle data = intent.getBundleExtra(PushListenerService.INTENT_SNS_NOTIFICATION_DATA);
            String message = PushListenerService.getMessage(data);

            new AlertDialog.Builder(Main_Onboarding.this)
                    .setTitle(R.string.push_demo_title)
                    .setMessage(message)
                    .setPositiveButton(android.R.string.ok, null)
                    .show();
        }
    };

    private final BroadcastReceiver settingsChangedReceiver = new BroadcastReceiver() {
        @Override
        public void onReceive(Context context, Intent intent) {
            Log.d(LOG_TAG, "Received settings changed local broadcast. Update theme colors.");
//            updateColor();
        }
    };
    /***********************************************************************************************/

    /********************************** Google Maps Methods ****************************************/
    /************************************************************************************************/
    public void theMapOnCreateMethod(){

        egoMap.theOnCreateMethod();
    }

    public void theMapOnStartMethod(){
        egoMap.theOnStartMethod();
    }

//    public void theMapOnResumeMethod(){
//        egoMap.theOnResumeMethod();
//    }

    public static void getNearbyUsers(int count){
        egoMap.PushLocation(count);
    }










    /***********************************************************************************************/
}

